
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
      
language: java
jdk:
  - oraclejdk8
  
cache:
  directories:
    - $HOME/.m2
    
before_cache:
  - rm -f $HOME/.m2/repository/io/cucumber
  
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --no-sandbox

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean install
  - mvn test -B
